### ISSUE TITLE
Will Tizen Maui and BlazorWebView work together?

### ISSUE THREAD

**Issue by sturlath** [Samsung/Tizen.NET#141]
Hi am struggling how to start creating my new mobile and Tv app. I want to use .net Maui and will start with the mobile app and then when you are ready I´ll implement that part.

**But** now I have a question before I start: Does Tizen.net and [BlazorWebView](https://egvijayanand.in/2021/11/13/net-maui-blazor/) play together?

That is could I program my app in BlazorWebView and then use Tizen.net to make it available in SmartTv´s?

**Comment by rookiejava** [comment]
Hi @sturlath! Thank you for reaching out.

>But now I have a question before I start: Does Tizen.net and [BlazorWebView](https://egvijayanand.in/2021/11/13/net-maui-blazor/) play together?

Definitely yes! Since Tizen 4.0, Tizen platform support .NET and Xamarin.Forms app as a first-class citizen.
As for .NET MAUI (including Blazor web view), we are developing a Tizen backend implementation through continuous collaboration with Microsoft .NET MAUI Team. Please refer to the PR below for detailed development status.
https://github.com/dotnet/maui/pull/2360 (This is still under review, but I hope this will merge soon. 😃 )

> That is could I program my app in BlazorWebView and then use Tizen.net to make it available in SmartTv´s?

Yes, you can! But there are some prerequisites. As you know, the BlazorWebView is requires .NET6 or higher. Unfortunately, existing Samsung Smart TVs are not supporting .NET6 yet. If Samsung Smart TV supports .NET6 (I'm not sure but, I expect it to be supported soon in a new model or upgrade), .NET MAU and BlazorWebView apps will naturally works on Samsung Smart TV.

You can find more demo apps operating in Tizen at the link below.
https://github.com/Samsung/Tizen.NET/wiki/.NET-MAUI-Tizen-Demos

Thanks!

**Comment by rookiejava** [comment]
Tizen backend PR on maui is merged last week. Let's enjoy!.
