### ISSUE TITLE
[Manifest] requires to set `version` and `package`/`appid` while it is already specified in common project file

### ISSUE THREAD

**Issue by xperiandri** [Samsung/Tizen.NET#166]
According to Visual Studio 2022 17.3 Preview 1.0 template Tizen manifest looks like this
``` XML
<manifest package="com.companyname.MauiApp" version="1.0.0" api-version="7" xmlns="http://tizen.org/ns/packages">
<profile name="common" />
<ui-application appid="com.companyname.MauiApp" exec="MauiApp.dll" multiple="false" nodisplay="false" taskmanage="true" type="dotnet" launch_mode="single">
```
while Android manifest and plist files no longer contain any information like `package="com.companyname.MauiApp"`, `appid="com.companyname.MauiApp"`, `<label>MauiApp</label>`, `<icon>appicon.xhigh.png</icon>`, `version="1.0.0"` because csproj file already contains them
``` XML
<!-- Display name -->
<ApplicationTitle>MauiApp</ApplicationTitle>

<!-- App Identifier -->
<ApplicationId>com.companyname.mauiapp</ApplicationId>

<!-- Versions -->
<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
<ApplicationVersion>1</ApplicationVersion>
...
<!-- App Icon -->
<MauiIcon Include="Resources\appicon.svg" ForegroundFile="Resources\appiconfg.svg" Color="#512BD4" />
```

where the icon is automatically produced from SVG in all the required formats and sizes

**Comment by JoonghyunCho** [comment]
Thanks for your great suggestions :)
`icon` is technically not required on the template because it will be regenerated at build time.
Other information like application title and id are still required because they don't sync with those on csproj now. However, in the point of MAUI's single project philosophy, it is definitely worth considering what will be the best for developer's experience.
I will put this idea on the list of considering for our improvements!
Thanks.

**Comment by JoonghyunCho** [comment]
Share app manifest items you mentioned are implemented and now released on the latest maui tizen.
Thanks for your interest on Tizen :)
