### ISSUE TITLE
How to Automate the application in Tizen OS on TV 

### ISSUE THREAD

**Issue by vasanthraj-git** [Samsung/Tizen.NET#178]
hi ., 
  We are planning to automate the APplication in Tizen OS , we want to know how we can proceed for the same ?
1) is Python supported on Tizen Studio if not which is the other language we need to pick 
2) our intention is to test on the device(TV) itself , do we have any commands just like ADB in android .

**Comment by JoonghyunCho** [comment]
Like it is mentioned on https://github.com/Samsung/Tizen.NET/issues/177, app automation on TV is not supported due to their security policy.
Tizen has `sdb` which is just like adb in Android. `sdb` in included in the baseline Tizen sdk(https://developer.samsung.com/tizen/blog/en-us/2019/01/16/install-tizen-baseline-sdk).
