### ISSUE TITLE
Tizen Workload failed install

### ISSUE THREAD

**Issue by DIMANRUS** [Samsung/Tizen.NET#217]
Hello. If I want to install any workload, it always fails to install Tizen and nothing is installed. This has been observed since .NET 7. If you need more information, I am ready to provide.
![image](https://user-images.githubusercontent.com/41239551/204859481-410665ee-bd05-4c95-bc51-502ea8245a3b.png)

**Comment by JoonghyunCho** [comment]
@DIMANRUS Sorry for the trouble. We will see what's going on over there.
Until the issue is fixed, you can first remove Tizen workload and try install other workloads as a work around.

You can remove Tizen workload with the following command in your console.
```
~$ dotnet workload uninstall tizen
```
Also remove `C:\Program Files\dotnet\sdk-manifests\7.0.100\samsung.net.sdk.tizen` folder for the full clean up.

In order to install Tizen workload back to your environment, re-launch your VS with VS tools for Tizen installed or checkout https://github.com/Samsung/Tizen.NET/wiki/Installing-Tizen-.NET-Workload for more.

Thanks.

**Comment by DIMANRUS** [comment]
I removed tizen workload. And tried install, but...
![image](https://user-images.githubusercontent.com/41239551/205817152-76bb5b81-99c5-48f7-8f40-f8d83687c7b7.png)

**Comment by JoonghyunCho** [comment]
Oh, I meant to remove Tizen workload -> dotnet workload install or update -> and then install Tizen workload .
Make sure you remove the manifest folder under Program Files when you remove Tizen workload.

**Comment by DIMANRUS** [comment]
I deleted it, then executed the script that is in the screenshot in the previous comment. Then I just tried to update and install something, but it still gives an error after that. I can record a video of all my actions.

**Comment by JoonghyunCho** [comment]
Installing script re-install the Tizen workload. After removing Tizen workload, Don't execute "workload-instll.ps1" again before you update and install something.

**Comment by DIMANRUS** [comment]
After removing and without install tizen workload all worked. But this script always run with launching Visual Studio (my second issue on Github) and again a mistake.

**Comment by DIMANRUS** [comment]
Works with this option. Thanks.
![image](https://user-images.githubusercontent.com/41239551/206199097-a756557b-acdd-4f89-8417-a84bcf020c09.png)
