### ISSUE TITLE
Is .Net Core SDK required if I will use only Web Application in VSCode?

### ISSUE THREAD

**Issue by matale** [Samsung/Tizen.NET#220]
I have installed the Tizen VSCode extension and I am getting an error that .Net Core SDK is missing, is this required even if I am not planning to do .Net development? I just want to make a Tizen TV Web application.  I am also getting errors in the output terminal that that the powershell script can not run because it is not digitally signed.
Pop up window shows
`
The .NET Core SDK cannot be located: A valid dotnet installation could not be found. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.`

Terminal shows
```
[20:53:08] Dotnet workload install Error: c:\personal\tizen\workload-install.ps1 : File C:\personal\tizen\workload-install.ps1 cannot be loaded. The file 
C:\personal\tizen\workload-install.ps1 is not digitally signed. You cannot run this script on the current system
```

**Comment by matale** [comment]
Still not sure but I gather that the VS Code Extension does not support developing Tizen TV Web applications, Tizen Studio seems to be the way for that, all the tools are very confusing to figure out what exactly you need.

**Comment by JoonghyunCho** [comment]
@matale Hello, the current VS tools bring the .NET development environment by default and installing workload is what it is. If you are just interested in developing something else, .net core sdk related errors will not affect you.
@sangwook96-lee can help you answering  about which tool is proper for you to develop TV web applications.

**Comment by sangwook96** [comment]
@matale , Hi,
Thank you very much for asking your questions here.
First, we developed TizenStudio to provide Tizen App Develop Environment.
But To have more Tizen users, Tizen supports C# languages for Tizen App.
So We chose Visual Studio IDE which is the best tool to develop C# apps and then we developed VS plugin(extension) to install VS IDE.
Firstly, VS plugin support Tizen.NET App but recently, we extend more language native and web, too.
Second, VSCoed Extension for Tizen, it has been developed a lightweight tool running on every os(windows, ubuntu,macOS)

As you mentioned, we think that we have a lot of loads to manage and develop TizenStudio/VS Extension/VSCode Extension.
We hope that many users use VS or VSCode Extension instead of TizenStudio IDE.
Then, we may move our efforts from TizenStudio to VS tools.


I would like to update support app types shortly.
1. TizenStudio
=> Support to develop Tizen Native app/Web app
=> Mainly TV App developers use it for developing Tizen TV Web Apps.
2. Visual Studio for Tizen
=> Support to develop Tizen Dotnet app/Natvie app/Web app
=> but mainly users use it for developing Tizen.NET apps (C#)

3. VSCode Ext
=> Support to develop Tizen Dotnet app/Natvie app/Web app
=> It is a new tool and a user can develop Tizen Apps as a lightweight tool based on the command line.

Thanks
