### ISSUE TITLE
Check certificate error [-12] failed

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#48]
I created a new samsung certificate and using this certificate I could debug on my Active watch. 
Then i unchecked the setting under Tools->Options->Tizen->Certification

![image](https://user-images.githubusercontent.com/10422347/71679080-066f1700-2d87-11ea-98b2-712f842f748a.png)

I debugged on emulator without certificate. I came back to that option and check the option again as in the image using before working certificate. This time debugging on the device not possible and Check certificate error [-12] failed is returned. If I create new certificate it works.
Why?

**Comment by sangwook96-lee** [comment]
Hi,
Thanks for asking it to us here.
In order to help you, we need to get more log information.
In the same your situation, Could you share your logs after changing the below values?

Tools->Options->Projects and Solutions->Build and Run
1. MSBuild project build output
Detailed
2. MSBuild project build log file
Detailed

**Comment by rookiejava** [comment]
@EmilAlipiev  could you give your information to us mentioned in above?

**Comment by EmilAlipiev** [comment]
I cannot reproduce this again. I assume that it was one time issue
