### ISSUE TITLE
Crash issue when the slider's Min value is 1 or higher

### ISSUE THREAD

**Issue by xbldx** [Samsung/Tizen.NET#78]
**Describe the bug**
Crash issue when the slider's Min value is 1 or higher

**To Reproduce**
Open the xaml file. Then insert the following slider code.
`<Slider Minimum="2" Value="2" Maximum="10"/>`

**Expected behavior**
There should be no crash.

**Screenshots**
[Error Code - RPI4]
Value is an invalid value for Minimum

[Error Code - Mobile Emulator]
System.ArgumentException: Value is an invalid value for Minimum (Parameter 'value')
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)

**Environment (please complete the following information):**
 - RPI4
 - Mobile Emulator

**Additional context**
PM asked to check the TC about this.

**Comment by JoonghyunCho** [comment]
Hello 😄 
Each property of `Slider` has the following default value, and `Slider` validates each value when it is set.

>Slider.Maximum : 1 (value must be bigger than Minimum)
>Slider.Minimum : 0  (value must be smaller than Maximum)
>Slider.Value: 0

From the given sample code in xaml
```
<Slider Minimum="2" Value="2" Maximum="10"/>
```
When the `Minimum` value is set to 2, it throws the ArgumentException because the value is bigger than the Maximum value at the moment which is 1.
Therefore, the following code will be ok.
```
<Slider  Maximum="10" Minimum="2" Value="2"/>
```

**Comment by Hackmodford** [comment]
🤦🏻‍♂️
