### ISSUE TITLE
Fix Default file name on log export

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.NET#82]
when I try to export logs from Device Manager. default file name is not a valid name on Windows as shown below.
not sure if the ip address and port is really needed :)

![image](https://user-images.githubusercontent.com/10422347/102641203-f9943080-415b-11eb-9ba2-25a15992f39c.png)

**Comment by rookiejava** [comment]
Thank you for reporting and suggestion.  

@sangwook96-lee and @winstone77 , Could you please take a look on this?

**Comment by dkson95** [comment]
@EmilAlipiev yes, this is related with remote device connected case for the ip with port attached to the filename. (expected behavior 

```
>sdb devices
List of devices attached
10.113.171.169:26101    device          0
```
If you can check the latest TizenStudio(https://developer.tizen.org/development/tizen-studio/download) you can modify the filename by:
![image](https://user-images.githubusercontent.com/17193661/109616331-61adbc80-7b78-11eb-9e68-e2cb43c23346.png)

Thank you.
